"""Aggregator / Analyst — builds the final StormReport.

P0: template-based synthesis over real aggregates (counts, clusters, curves).
Roadmap: the numeric aggregates stay exactly as computed here, and the
Fireworks-hosted Gemma 27B analyst agent rewrites `summary`, per-segment
`insight` strings and `recommendations` from those aggregates (numbers are
never generated by the LLM — it only narrates them; see docs/architecture.md).
"""

from __future__ import annotations

from collections import Counter

from ...schemas.persona import Persona
from ...schemas.quality import QualityMetrics
from ...schemas.reaction import PersonaReaction
from ...schemas.report import (
    AdoptionSummary,
    KillQuoteContext,
    Recommendation,
    SegmentReport,
    StormReport,
)
from ...schemas.storm import StormCreateRequest
from ...utils.text import normalize_objection
from ..stimulus_parser import StimulusFeatures
from .objections import cluster_objections
from .pricing import average_wtp, build_price_curve


def build_report(
    storm_id: str,
    request: StormCreateRequest,
    personas: list[Persona],
    reactions: list[PersonaReaction],
    features: StimulusFeatures,
    quality: QualityMetrics,
) -> StormReport:
    adoption = AdoptionSummary(
        green=sum(1 for r in reactions if r.status == "green"),
        yellow=sum(1 for r in reactions if r.status == "yellow"),
        red=sum(1 for r in reactions if r.status == "red"),
    )
    segments = _segment_reports(reactions)
    objections = cluster_objections(reactions)
    curve = build_price_curve(reactions, features)
    avg_wtp = average_wtp(reactions)
    kill_quote, kill_ctx = _kill_quote(personas, reactions, features)
    recommendations = _recommendations(request, features, quality, objections,
                                       segments, curve, adoption, len(reactions))
    summary = _summary(request, adoption, objections, avg_wtp, quality, len(reactions))

    return StormReport(
        storm_id=storm_id,
        title=request.title,
        summary=summary,
        adoption=adoption,
        segments=segments,
        top_objections=objections,
        price_sensitivity=curve,
        kill_quote=kill_quote,
        kill_quote_context=kill_ctx,
        quality=quality,
        recommendations=recommendations,
        persona_count=len(reactions),
        stimulus_type=request.stimulus_type.value,
        target_market=request.target_market.value,
        avg_max_price=avg_wtp,
    )


# ------------------------------------------------------------------- segments

def _segment_reports(reactions: list[PersonaReaction]) -> list[SegmentReport]:
    by_seg: dict[str, list[PersonaReaction]] = {}
    for r in reactions:
        by_seg.setdefault(r.segment or "unknown", []).append(r)

    out: list[SegmentReport] = []
    for seg, rs in sorted(by_seg.items(), key=lambda kv: -len(kv[1])):
        n = len(rs)
        green = sum(1 for r in rs if r.status == "green")
        yellow = sum(1 for r in rs if r.status == "yellow")
        red = sum(1 for r in rs if r.status == "red")
        top_obj = _top_objection(rs)
        adoption_rate = green / n
        avg_like = sum(r.buy_likelihood for r in rs) / n
        avg_price = sum(r.max_price for r in rs) / n

        if adoption_rate >= 0.5:
            insight = (f"Strongest segment ({adoption_rate:.0%} likely buyers) — "
                       f"lead go-to-market here; residual concern: {top_obj}.")
        elif red / n >= 0.5:
            insight = (f"High-risk segment ({red / n:.0%} rejectors) — "
                       f"dominant blocker: {top_obj}. Fix or deprioritize.")
        else:
            insight = (f"Persuadable middle ({yellow / n:.0%} undecided) — "
                       f"converting them hinges on: {top_obj}.")

        out.append(SegmentReport(
            segment=seg, personas=n, green=green, yellow=yellow, red=red,
            adoption_rate=round(adoption_rate, 3),
            avg_buy_likelihood=round(avg_like, 3),
            avg_max_price=round(avg_price, 2),
            top_objection=top_obj,
            insight=insight,
        ))
    return out


def _top_objection(rs: list[PersonaReaction]) -> str:
    counts: Counter[str] = Counter()
    raw: dict[str, str] = {}
    for r in rs:
        if r.first_objection.strip():
            key = normalize_objection(r.first_objection)
            counts[key] += 1
            raw.setdefault(key, r.first_objection)
    if not counts:
        return "none recorded"
    return raw[counts.most_common(1)[0][0]]


# ------------------------------------------------------------------ kill quote

def _kill_quote(personas: list[Persona], reactions: list[PersonaReaction],
                features: StimulusFeatures) -> tuple[str, KillQuoteContext | None]:
    """Most damaging quote: a low-intent, high-skepticism persona whose quote is
    specific (references the stimulus) and substantial. Deterministic scoring —
    no cherry-picking, and the context object shows who said it."""
    by_id = {p.persona_id: p for p in personas}
    best_score, best = -1.0, None
    for r in reactions:
        if r.status != "red":
            continue
        p = by_id.get(r.persona_id)
        if p is None:
            continue
        specificity = 1.0 if any(a in r.quote.lower() for a in features.anchor_set()) else 0.4
        length_bonus = min(1.0, len(r.quote) / 120.0)
        score = (1.0 - r.buy_likelihood) * 0.4 + p.skepticism * 0.3 \
            + specificity * 0.2 + length_bonus * 0.1
        if score > best_score:
            best_score, best = score, (r, p)

    if best is None:
        return "No rejection strong enough to produce a kill quote.", None
    r, p = best
    return r.quote, KillQuoteContext(
        persona_id=p.persona_id, segment=p.segment,
        buy_likelihood=r.buy_likelihood, skepticism=p.skepticism,
    )


# -------------------------------------------------------------- recommendations

def _recommendations(request, features, quality, objections, segments, curve,
                     adoption, total) -> list[Recommendation]:
    recs: list[Recommendation] = []

    if objections:
        top = objections[0]
        if top.share >= 0.12:
            recs.append(Recommendation(
                title=f"Neutralize the #1 objection: “{top.label}”",
                detail=(f"{top.share:.0%} of the swarm raised this "
                        f"(hits {', '.join(top.top_segments) or 'multiple segments'} hardest). "
                        "Address it directly in the first screen of copy."),
                priority="now",
            ))
    if not features.has_pricing:
        recs.append(Recommendation(
            title="Publish visible pricing",
            detail="No price was detected in the stimulus. Hidden pricing is a top synthetic "
                   "objection and typically the cheapest fix before real-user testing.",
            priority="now",
        ))
    if not features.has_proof:
        recs.append(Recommendation(
            title="Add one concrete proof point",
            detail="The stimulus contains claims but no numbers, case study, or testimonial. "
                   "High-skepticism personas defaulted to rejection because of it.",
            priority="now",
        ))
    # Highest price the majority still accepts (curve is ascending in price,
    # descending in share — take the LAST point above 50%).
    fair = max((pt for pt in curve if pt.share_willing >= 0.5),
               key=lambda p: p.price, default=None)
    if fair:
        recs.append(Recommendation(
            title=f"Price-test around ${fair.price:g}",
            detail=f"{fair.share_willing:.0%} of the swarm accepts ${fair.price:g}. "
                   "Use it as the midpoint of a Van Westendorp test with real users.",
            priority="next",
        ))
    weakest = min(segments, key=lambda s: s.adoption_rate, default=None)
    if weakest and weakest.adoption_rate < 0.25 and len(segments) > 1:
        recs.append(Recommendation(
            title=f"Re-message or deprioritize: {weakest.segment}",
            detail=f"Only {weakest.adoption_rate:.0%} adoption; blocker: {weakest.top_objection}.",
            priority="next",
        ))
    if quality.collapse_risk != "low":
        recs.append(Recommendation(
            title="Treat this run as directional only",
            detail=f"Collapse risk is {quality.collapse_risk} — reaction diversity is below "
                   "target. Re-run with higher persona diversity before acting on numbers.",
            priority="now",
        ))
    # Positioning rule: ALWAYS end by pointing at real research.
    recs.append(Recommendation(
        title="Validate top objections with real humans",
        detail="Wind-tunnel results are hypotheses. A 20-30 person survey targeting the top "
               f"{min(3, len(objections))} objections above will confirm or kill them for "
               "a fraction of a failed-launch cost.",
        priority="next",
    ))
    return recs[:6]


# ---------------------------------------------------------------------- summary

def _summary(request, adoption, objections, avg_wtp, quality, total) -> str:
    total = max(1, total)
    g, y, r = adoption.green, adoption.yellow, adoption.red
    top_line = (f"{g / total:.0%} of {total} synthetic personas showed buy intent, "
                f"{y / total:.0%} are persuadable but unconvinced, and "
                f"{r / total:.0%} rejected the {request.stimulus_type.value.replace('_', ' ')}.")
    obj_line = ""
    if objections:
        obj_line = (f" The dominant objection — “{objections[0].label}” — "
                    f"accounts for {objections[0].share:.0%} of first objections.")
    wtp_line = f" Average stated willingness to pay is ${avg_wtp:g}."
    trust_line = (f" Signal quality: collapse risk {quality.collapse_risk}, "
                  f"segment variance {quality.segment_variance}, "
                  f"benchmark confidence {quality.benchmark_confidence} — "
                  "treat as pre-research hypotheses, not validated demand.")
    return top_line + obj_line + wtp_line + trust_line
